-- =============================================================================
-- Migration: 20260911000003_kiosk_and_redflag_integrity_closure.sql
-- Description: Final Kiosk Revocation, Client-Wiring & Red-Flag Integrity Closure
--              1. Locks down red_flag_events: revokes direct INSERT/UPDATE/DELETE
--                 from authenticated and anon. Preserves facility-scoped read.
--              2. Locks down kiosk_capability_revocations: revokes direct
--                 INSERT/UPDATE/DELETE from authenticated and anon.
--              3. Scopes kiosk_capability_revocations SELECT policy to same facility
--                 via intake_sessions.facility_id = current_user_facility().
--              4. Introduces rpc_clinician_revoke_session for atomic, facility-
--                 validated clinician session revocation with legal audit trail.
-- =============================================================================

-- =============================================================================
-- 1. RED_FLAG_EVENTS CLINICAL EVIDENCE MUTABILITY LOCKDOWN
-- =============================================================================
-- Ensure RLS is active
ALTER TABLE public.red_flag_events ENABLE ROW LEVEL SECURITY;

-- Drop all direct write policies for authenticated users
DROP POLICY IF EXISTS "Clinicians can insert red flags" ON public.red_flag_events;
DROP POLICY IF EXISTS "Clinicians can update red flags" ON public.red_flag_events;
DROP POLICY IF EXISTS "Red flag events facility scoped insert" ON public.red_flag_events;
DROP POLICY IF EXISTS "Red flag events facility scoped update" ON public.red_flag_events;
DROP POLICY IF EXISTS "Allow authenticated clinicians and kiosk to insert red flags" ON public.red_flag_events;

-- Red-flag events are clinical evidence generated by the rules engine and acknowledged via RPC.
-- Direct INSERT, UPDATE, DELETE are strictly revoked from client roles.
REVOKE ALL ON public.red_flag_events FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.red_flag_events FROM authenticated;
GRANT SELECT ON public.red_flag_events TO authenticated;
GRANT ALL ON public.red_flag_events TO service_role;

-- =============================================================================
-- 2. KIOSK_CAPABILITY_REVOCATIONS FACILITY SCOPING & WRITE LOCKDOWN
-- =============================================================================
-- Ensure RLS is active
ALTER TABLE public.kiosk_capability_revocations ENABLE ROW LEVEL SECURITY;

-- Drop legacy permissive or unstructured policies
DROP POLICY IF EXISTS "Allow authenticated clinicians and kiosk RPC to view revocations" ON public.kiosk_capability_revocations;
DROP POLICY IF EXISTS "Clinicians can view revocations" ON public.kiosk_capability_revocations;
DROP POLICY IF EXISTS "Clinicians can insert revocations" ON public.kiosk_capability_revocations;
DROP POLICY IF EXISTS "Clinicians can update revocations" ON public.kiosk_capability_revocations;
DROP POLICY IF EXISTS "Kiosk capability revocations facility scoped read" ON public.kiosk_capability_revocations;

-- Recreate SELECT policy with strict facility boundary scoping via intake_sessions
CREATE POLICY "Kiosk capability revocations facility scoped read"
  ON public.kiosk_capability_revocations FOR SELECT
  TO authenticated
  USING (
    public.current_user_role() IN ('doctor', 'clinician', 'admin') AND (
      public.current_user_role() = 'admin' OR
      EXISTS (
        SELECT 1 FROM public.intake_sessions s
        WHERE s.id = kiosk_capability_revocations.session_id
          AND s.facility_id IS NOT NULL
          AND s.facility_id = public.current_user_facility()
      )
    )
  );

-- Direct writes to kiosk_capability_revocations are revoked from authenticated and anon.
-- Revocations must occur through atomic RPCs (rpc_revoke_kiosk_session or rpc_clinician_revoke_session).
REVOKE ALL ON public.kiosk_capability_revocations FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.kiosk_capability_revocations FROM authenticated;
GRANT SELECT ON public.kiosk_capability_revocations TO authenticated;
GRANT ALL ON public.kiosk_capability_revocations TO service_role;

-- =============================================================================
-- 3. CLINICIAN SESSION REVOCATION RPC (rpc_clinician_revoke_session)
-- =============================================================================
-- Provides an atomic, facility-validated revocation path for authenticated clinicians.
CREATE OR REPLACE FUNCTION public.rpc_clinician_revoke_session(
  p_session_id UUID,
  p_reason TEXT DEFAULT 'clinician_revoked',
  p_target_status TEXT DEFAULT 'abandoned'
) RETURNS VOID AS $$
DECLARE
  v_caller_id UUID;
  v_caller_role TEXT;
  v_caller_facility TEXT;
  v_caller_active BOOLEAN;
  v_session public.intake_sessions;
  v_now TIMESTAMPTZ := now();
BEGIN
  -- 1. Derive caller from auth.uid()
  v_caller_id := auth.uid();
  IF v_caller_id IS NULL THEN
    RAISE EXCEPTION 'UNAUTHORIZED: Authentication session required to revoke kiosk session';
  END IF;

  -- 2. Validate active clinician profile
  SELECT role, facility_id, COALESCE(is_active, true)
  INTO v_caller_role, v_caller_facility, v_caller_active
  FROM public.profiles WHERE id = v_caller_id;

  IF NOT FOUND OR v_caller_active IS NOT TRUE THEN
    RAISE EXCEPTION 'FORBIDDEN: Clinician profile is missing or inactive';
  END IF;

  IF v_caller_role NOT IN ('doctor', 'clinician', 'admin') THEN
    RAISE EXCEPTION 'FORBIDDEN: Role % cannot revoke kiosk sessions', v_caller_role;
  END IF;

  -- 3. Lock and verify session
  SELECT * INTO v_session FROM public.intake_sessions WHERE id = p_session_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'SESSION_NOT_FOUND: Intake session % does not exist', p_session_id;
  END IF;

  -- 4. Verify facility boundaries (admin can revoke across facilities)
  IF v_caller_role != 'admin' THEN
    IF v_caller_facility IS NULL OR v_session.facility_id IS NULL OR v_caller_facility != v_session.facility_id THEN
      RAISE EXCEPTION 'FORBIDDEN: Clinician facility % does not match session facility %',
        COALESCE(v_caller_facility, 'none'), COALESCE(v_session.facility_id, 'none');
    END IF;
  END IF;

  -- 5. Update intake_sessions
  UPDATE public.intake_sessions
  SET status = COALESCE(p_target_status, 'abandoned'),
      completed_at = v_now
  WHERE id = p_session_id;

  -- 6. Upsert into kiosk_capability_revocations
  INSERT INTO public.kiosk_capability_revocations (
    session_id,
    revoked_at,
    reason,
    expires_at
  ) VALUES (
    p_session_id,
    v_now,
    COALESCE(p_reason, 'clinician_revoked'),
    v_now + INTERVAL '7 days'
  )
  ON CONFLICT (session_id) DO UPDATE
  SET revoked_at = EXCLUDED.revoked_at,
      reason = EXCLUDED.reason,
      expires_at = EXCLUDED.expires_at;

  -- 7. Audit log entry
  INSERT INTO public.audit_logs (
    actor_id,
    action,
    resource_type,
    resource_id,
    metadata,
    created_at
  ) VALUES (
    v_caller_id::text,
    'KIOSK_SESSION_REVOKED',
    'intake_sessions',
    p_session_id::text,
    jsonb_build_object(
      'reason', COALESCE(p_reason, 'clinician_revoked'),
      'targetStatus', COALESCE(p_target_status, 'abandoned'),
      'actorRole', v_caller_role,
      'facilityId', v_session.facility_id
    ),
    v_now
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

-- Revoke all permissions from anon and PUBLIC; grant execute to authenticated and service_role
REVOKE ALL ON FUNCTION public.rpc_clinician_revoke_session(UUID, TEXT, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rpc_clinician_revoke_session(UUID, TEXT, TEXT) TO authenticated, service_role;
